Prompt workspace picker if file does not exist
ytakhs/vscode-advanced-open-file pull request #103
Opened 2024-03-10 19:22 UTC by garaemon

The URI of the text editor does not a valid for sometimes.
For example, an [`edamagit`](https://github.com/kahole/edamagit/blob/52546589349022a73bf3556cc348c10deb9d3a47/src/views/magitStatusView.ts#L25) view uses `status.magit` as the uri.

In those cases, this patch shows a picker to choose workspaces rather than showing some invalid paths.

2024-03-16 17:25 UTC, garaemon commented
@ytakhs Could you review this? Thanks!

2024-09-14 14:01 UTC, ytakhs requested changes
Apologies for the delay in the review. 
I’ve added a few comments, so please take a look!

2024-09-14 19:01 UTC, garaemon commented on src/extension.ts
> +    if (fs.existsSync(currentEditor.document.uri.path)) {
@ytakhs Thank you for reviewing. Updated. Could you review it again?

2024-09-16 13:05 UTC, ytakhs approved these changes
Looks good 👍 Thank you!

2024-09-16 13:06 UTC, merged

2024-09-17 02:35 UTC, garaemon commented
@ytakhs Thank you for merging this. Could you release a new version of the extension?

2024-09-17 13:44 UTC, ytakhs commented
@garaemon I've published it, so please give it a try!

2024-09-17 19:07 UTC, garaemon commented
@ytakhs Thank you! I confirmed that the latest version works as I expected.